//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActuallyPurchase_Tbl
    {
        public int ActuallyPurchaseId { get; set; }
        public int PurchasesHistoryId { get; set; }
        public int ProductId { get; set; }
        public int Amount { get; set; }
        public Nullable<int> PurchasePrognosisId { get; set; }
    
        public virtual Product_Tbl Product_Tbl { get; set; }
        public virtual PurchasePrognosis_Tbl PurchasePrognosis_Tbl { get; set; }
        public virtual PurchasesHistory_Tbl PurchasesHistory_Tbl { get; set; }
    }
}
