//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviourPattern_Tbl
    {
        public int BehaviourPatternId { get; set; }
        public Classification Status { get; set; }
        public Nullable<int> EveryXMonthsBuy { get; set; }
        public Nullable<int> Amount { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public string NameOfEvent { get; set; }
        public Nullable<bool> IsNewProduct { get; set; }
        public Nullable<int> TimesOfCancelation { get; set; }
        public Nullable<int> TimesOfAmountChange { get; set; }
        public Nullable<int> TimesNotFoundInPrognosis { get; set; }
        public Nullable<int> XTimesOnMonthBuy { get; set; }
        public Nullable<System.DateTime> LastPurchaseDate { get; set; }
    
        public virtual Product_Tbl Product_Tbl { get; set; }
        public virtual Customer_Tbl Customer_Tbl { get; set; }
        public virtual Product_Tbl Product_Tbl1 { get; set; }
    }
}
