//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    
    public enum Classification : int
    {
        Unknown = 0,
        Monthly = 1,
        Frequently = 2,
        Periodic = 3,
        Event = 4
    }
}
