//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    
    public enum Frequency : int
    {
        unknown = 0,
        annual = 1,
        frequently = 2,
        monthly = 3,
        seasonal = 4
    }
}
