//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Tbl()
        {
            this.ActuallyPurchase_Tbl = new HashSet<ActuallyPurchase_Tbl>();
            this.BehaviourPattern_Tbl = new HashSet<BehaviourPattern_Tbl>();
            this.PurchasePrognosis_Tbl = new HashSet<PurchasePrognosis_Tbl>();
            this.BehaviourPattern_Tbl1 = new HashSet<BehaviourPattern_Tbl>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public int ProductCategoryId { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActuallyPurchase_Tbl> ActuallyPurchase_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehaviourPattern_Tbl> BehaviourPattern_Tbl { get; set; }
        public virtual ProductCategory_Tbl ProductCategory_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePrognosis_Tbl> PurchasePrognosis_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehaviourPattern_Tbl> BehaviourPattern_Tbl1 { get; set; }
    }
}
