//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasesHistory_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchasesHistory_Tbl()
        {
            this.ActuallyPurchase_Tbl = new HashSet<ActuallyPurchase_Tbl>();
            this.PurchasePrognosis_Tbl = new HashSet<PurchasePrognosis_Tbl>();
        }
    
        public int PurchasesHistoryId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Description { get; set; }
        public Nullable<bool> BelongToCurrentYear { get; set; }
        public int HebrewDateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActuallyPurchase_Tbl> ActuallyPurchase_Tbl { get; set; }
        public virtual Customer_Tbl Customer_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePrognosis_Tbl> PurchasePrognosis_Tbl { get; set; }
        public virtual HebrewDate_Tbl HebrewDate_Tbl { get; set; }
    }
}
