//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasePrognosis_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchasePrognosis_Tbl()
        {
            this.ActuallyPurchase_Tbl = new HashSet<ActuallyPurchase_Tbl>();
        }
    
        public int PurchasePrognosisId { get; set; }
        public int PurchasesHistoryId { get; set; }
        public int ProductId { get; set; }
        public int Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActuallyPurchase_Tbl> ActuallyPurchase_Tbl { get; set; }
        public virtual Product_Tbl Product_Tbl { get; set; }
        public virtual PurchasesHistory_Tbl PurchasesHistory_Tbl { get; set; }
    }
}
